In [2]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a = np.arange(12)
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [5]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
for cell in np.nditer(a, order='C'):
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [7]:
for cell in np.nditer(a, order='F'):
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [8]:
for cell in np.nditer(a, order='F', flags=['external_loop']):
    print(cell)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
for cell in np.nditer(a, op_flags=['readwrite']):
    cell[...] = cell * cell

In [10]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [11]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [12]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 3
25 3
36 3
49 3
64 3
81 3
100 3
121 3
0 7
1 7
4 7
9 7
16 7
25 7
36 7
49 7
64 7
81 7
100 7
121 7
0 11
1 11
4 11
9 11
16 11
25 11
36 11
49 11
64 11
81 11
100 11
121 11


In [13]:
c = np.arange(3, 19, 5).reshape(4,1)
c

array([[ 3],
       [ 8],
       [13],
       [18]])

THIS LINE WILL GENERATE AN ERROR

In [14]:
for x,y in np.nditer([a,c]):
    print(x,y)

0 3
1 3
4 3
9 3
16 3
25 3
36 3
49 3
64 3
81 3
100 3
121 3
0 8
1 8
4 8
9 8
16 8
25 8
36 8
49 8
64 8
81 8
100 8
121 8
0 13
1 13
4 13
9 13
16 13
25 13
36 13
49 13
64 13
81 13
100 13
121 13
0 18
1 18
4 18
9 18
16 18
25 18
36 18
49 18
64 18
81 18
100 18
121 18
